baseURL = "https://timedilationv2.github.io/checkcheck/"
languageCode = "en-us"
title = "SuperAi"
theme = "PaperMod"
paginate = 10

[params]
  author = "Arsalan Khan"
  description = "AI Research Blog — Papers, Thoughts, and Explorations"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 2
